# .github/workflows/deploy.yml
name: Deploy to Server

on:
  push:
    branches:
      - main  # Jalankan workflow ketika push ke branch main

jobs:
  deploy:
    name: SSH Git Pull to Production Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Pull latest code on server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
          cd /var/www/recruitments/recruitments &&
          git reset --hard &&
          git pull origin main &&
          php artisan config:cache
        "
